#ifndef __MyMainFrame__
#define __MyMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "mainframe.h"

/** Implementing MainFrame */
class MyMainFrame : public MainFrame
{
protected:
	// Handlers for MainFrame events.	
	void MenuItem1Clicked( wxCommandEvent& event );
	void MenuItem2Clicked( wxCommandEvent& event );
	void MenuItem3Clicked( wxCommandEvent& event );
	void MenuItem4Clicked( wxCommandEvent& event );	
	void CheckBox2Clicked( wxCommandEvent& event );
	void RadioBox1Clicked( wxCommandEvent& event );
	void TextCtrl3TextEnter( wxCommandEvent& event );
	void CheckBox3Clicked( wxCommandEvent& event );
	void ColourPicker1Changed( wxColourPickerEvent& event );
	void Button1Clicked( wxCommandEvent& event );
	void Button2Clicked( wxCommandEvent& event );
	void TextCtrl4TextEnter( wxCommandEvent& event );
	void TextCtrl5TextEnter( wxCommandEvent& event );
	void MenuItem5Clicked( wxCommandEvent& event );
	void MenuItem6Clicked( wxCommandEvent& event );	
	void PropertyGrid1Changed( wxCommandEvent& event );

public:
	/** Constructor */
	MyMainFrame( wxWindow* parent );
	void AddMaterial(DWORD id,FireCube::Material mat);

	map<DWORD,FireCube::Material> materialMap;
};

#endif // __MyMainFrame__
