#ifndef __MyMainFrame__
#define __MyMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "mainframe.h"

/** Implementing MainFrame */
class MyMainFrame : public MainFrame
{
public:
	/** Constructor */
	MyMainFrame( wxWindow* parent );
	void MenuItem1Clicked( wxCommandEvent& event );
	void MenuItem2Clicked( wxCommandEvent& event );
	void MenuItem3Clicked( wxCommandEvent& event );
	void MenuItem4Clicked( wxCommandEvent& event );
	void MenuItem5Clicked( wxCommandEvent& event );
	void MenuItem6Clicked( wxCommandEvent& event );

	string currentFile;
};

#endif // __MyMainFrame__
