#ifndef __MyMainFrame__
#define __MyMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "mainframe.h"

/** Implementing MainFrame */
class MyMainFrame : public MainFrame
{
protected:
	// Handlers for MainFrame events.	
	void MenuItem1Clicked( wxCommandEvent& event );
	void MenuItem2Clicked( wxCommandEvent& event );
	void MenuItem3Clicked( wxCommandEvent& event );
	void MenuItem4Clicked( wxCommandEvent& event );
	void MenuItem5Clicked( wxCommandEvent& event );
	void MenuItem6Clicked( wxCommandEvent& event );
	void MenuItem7Clicked( wxCommandEvent& event );
	void MenuItem8Clicked( wxCommandEvent& event );
	void MenuItem9Clicked( wxCommandEvent& event );

public:
	/** Constructor */
	MyMainFrame( wxWindow* parent );
};

#endif // __MyMainFrame__
