#pragma once

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "mainframe.h"
#include "FireCube.h"

class MyApp;
class NodeDescriptor;
class SceneDescriptor;

/** Implementing MainFrame */
class MainFrameImpl : public MainFrame
{
	protected:
		// Handlers for MainFrame events.
		void MyButtonClicked( wxCommandEvent& event );
		void LoadMeshClicked(wxCommandEvent& event);
		virtual void UndoClicked(wxCommandEvent& event);
		virtual void RedoClicked(wxCommandEvent& event);

		MyApp *theApp;
		FireCube::Engine *engine;
		SceneDescriptor *sceneDescriptor;
		NodeDescriptor *rootDescriptor;
		EditorState *editorState;
	public:
		/** Constructor */
		MainFrameImpl( wxWindow* parent );	

		void SetSceneDescriptor(SceneDescriptor *sceneDescriptor);
	
};
