#pragma once

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "mainframe.h"
#include "FireCube.h"
#include "Descriptors/NodeDescriptor.h"

class MyApp;
class SceneSettings;
class BaseComponentPanelImpl;
class Command;
class ComponentDescriptor;
class MaterialEditorPanelImpl;
class AssetBrowserPanelImpl;
class ScriptEditorFrameImpl;

/** Implementing MainFrame */
class MainFrameImpl : public MainFrame, public FireCube::Object
{
	FIRECUBE_OBJECT(MainFrameImpl)
	protected:
		// Handlers for MainFrame events.		
		virtual void UndoClicked(wxCommandEvent& event) override;
		virtual void RedoClicked(wxCommandEvent& event) override;
		virtual void SaveClicked(wxCommandEvent& event) override;
		virtual void SaveAsClicked(wxCommandEvent& event) override;
		virtual void OpenClicked(wxCommandEvent& event) override;
		virtual void NewClicked(wxCommandEvent& event) override;
		virtual void AddMeshClicked(wxCommandEvent& event) override;
		virtual void SceneTreeSelectionChanged(wxTreeEvent& event) override;
		virtual void SceneTreeEndLabelEdit(wxTreeEvent& event) override;
		virtual void ViewSceneHierarchyClicked(wxCommandEvent& event) override;
		virtual void ViewInspectorClicked(wxCommandEvent& event) override;
		virtual void ViewMaterialEditorClicked(wxCommandEvent& event) override;
		virtual void ViewAssetBrowserClicked(wxCommandEvent& event) override;
		virtual void ViewScriptEditorClicked(wxCommandEvent& event) override;
		virtual void SceneTreeBeginDrag(wxTreeEvent& event) override;
		virtual void SceneTreeEndDrag(wxTreeEvent& event) override;
		virtual void PaneClose(wxAuiManagerEvent& event) override;
		virtual void AddStaticModelClicked(wxCommandEvent& event) override;
		virtual void AddLightClicked(wxCommandEvent& event) override;
		virtual void AddLuaScriptClicked(wxCommandEvent& event) override;
		virtual void AddCollisionShapeClicked(wxCommandEvent& event) override;
		virtual void AddCharacterControllerClicked(wxCommandEvent& event) override;
		virtual void AddBoxClicked(wxCommandEvent& event) override;
		virtual void AddPlaneClicked(wxCommandEvent& event) override;
		virtual void AddSphereClicked(wxCommandEvent& event) override;
		virtual void AddRigidBodyClicked(wxCommandEvent& event) override;
		virtual void AddParticleEmitterClicked(wxCommandEvent& event) override;
		virtual void AddCameraClicked(wxCommandEvent& event) override;
		virtual void AddNodeClicked(wxCommandEvent& event) override;
		virtual void SceneTreeKeyUp(wxKeyEvent& event) override;
		virtual void SceneTreeItemMenu(wxTreeEvent& event) override;
		virtual void CameraChoiceChanged(wxCommandEvent& event) override;
		virtual void TranslateToolClicked(wxCommandEvent& event) override;
		virtual void RotateToolClicked(wxCommandEvent& event) override;
		virtual void ScaleToolClicked(wxCommandEvent& event) override;
		void ComponentAdded(ComponentDescriptor *componentDesc);
		void ComponentRemoved(ComponentDescriptor *componentDesc);
		void AddComponentPanel(ComponentDescriptor *componentDesc);
		void RemoveComponentPanel(ComponentDescriptor *componentDesc);
		void SelectedNodeChanged(NodeDescriptor *nodeDesc);
		void NodeAdded(NodeDescriptor *nodeDesc);
		void NodeRemoved(NodeDescriptor *nodeDesc);
		void NodeRenamed(NodeDescriptor *nodeDesc);
		void UpdateInpsectorPane();		
		void UpdateUndoRedoMenu(Command *command);		
		void SetAllPanelsVisibility(bool visible);
		void LoadSettingsFile();
		void WriteSettingsFile();
		void RecentFileClicked(wxCommandEvent& event);		
		virtual void OnClose(wxCloseEvent& event);
		void OpenSceneFile(const std::string &filename);
		virtual void OnExitClicked(wxCommandEvent& event);
		void Reset();
		void NewSceneCreated();
		void ShowMaterialEditor();		
		void EditScript(const std::string &filename);
		void UpdateCamerasList();
		void CollectCameras(NodeDescriptor *node);
		void SwitchedToTranslateGizmo();
		void SwitchedToRotateGizmo();
		void SwitchedToScaleGizmo();

		MyApp *theApp;
		FireCube::Engine *engine;
		FireCube::Scene *scene;
		FireCube::Node *root;
		NodeDescriptor rootDesc;
		EditorState *editorState;
		SceneSettings *sceneSettings;

		std::map<NodeDescriptor *, wxTreeItemId> nodeToTreeItem;
		std::map<wxTreeItemId, NodeDescriptor *> treeItemToNode;
		
		wxTreeItemId dragItem;		
		std::vector<BaseComponentPanelImpl *> currentComponentPanels;
		std::vector<std::string> recentSceneFiles;
		std::vector<wxMenuItem *> recentSceneFilesMenuItems;

		MaterialEditorPanelImpl *materialEditorPanel;
		AssetBrowserPanelImpl *assetBrowserPanel;				
		ScriptEditorFrameImpl *scriptEditorFrame;				

public:
		/** Constructor */
		MainFrameImpl( wxWindow* parent );	

		void SetScene(FireCube::Scene *scene);
	
};
